
repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=142]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      additional_dependencies: [flake8-docstrings]
      args: [--max-line-length=142]
      types: ['python']
      overrides:
        - exclude: src/core/migrations
          extend-ignore: D100,D101,D102,D103,D104,D105,D106,D107

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
