- name: install required packages
  package:
    name:
    - postgresql
    - acl
    state: present

- name: install python deps
  pip:
    name:
    - psycopg2
    state: present

- name: create a database
  become_user: postgres
  postgresql_db:
    name: "{{ taranisng_database_database }}"
    encoding: UTF-8
    state: present
  vars:
    ansible_ssh_pipelining: true
    allow_world_readable_tmpfiles: true

- name: create a database user
  become_user: postgres
  postgresql_user:
    db: "{{ taranisng_database_database }}"
    name: "{{ taranisng_database_user }}"
    password: "{{  taranisng_database_password }}"
    priv: ALL
    state: present
  vars:
    ansible_ssh_pipelining: true
    allow_world_readable_tmpfiles: true

