- name: install the web server and wsgi
  package:
    name:
    - apache2
    - libapache2-mod-wsgi-py3

- name: enable the wsgi module
  apache2_module:
    name: wsgi
    state: present
  notify: apache2 restart

- name: deploy configuration file for unencrypted backend
  template:
    src: taranis-ng-api.conf.j2
    dest: /etc/apache2/sites-available/taranis-ng-api.conf
  notify: apache2 restart

- name: make sure an API webroot directory exists
  file:
    path: "{{ taranisng_root }}/taranis-ng-core"
    state: directory
    recurse: yes
    owner: "{{ taranisng_installation_user }}"
    group: "{{ taranisng_installation_group }}"

- name: enable the site
  command: a2ensite taranis-ng-api
  notify: apache2 restart

- name: Reload if needed
  meta: flush_handlers
