# web server
taranisng_hostname_gui: www.taranisng.local
taranisng_hostname_api: api.taranisng.local

taranisng_installation_user: taranisng
taranisng_installation_group: taranisng

taranisng_api_uri: "https://{{ taranisng_hostname_api }}/api"

taranisng_install_webserver: true
taranisng_gui_webroot: "/var/www/taranis-ng-gui"
taranisng_accesslog_gui: "/var/log/apache2/{{ taranisng_hostname_gui }}_access.log"
taranisng_errorlog_gui: "/var/log/apache2/{{ taranisng_hostname_gui }}_error.log"
