# inventory file where everything is just on a single host

all:
  hosts:
    www.taranisng.local:
      ansible_host: 192.168.56.101
      #ansible_host: 127.0.0.1
      #ansible_port: 2222
      ansible_user: taranisng
      ansible_become_password: taranisng
      ansible_python_interpreter: python3

