# sample data

- name: uncomment import test
  lineinfile:
    path: "{{ taranisng_root }}/taranis-ng-core/app.py"
    regexp: '#? ?z?import test'
    line: '        import test'

- name: run the app manually for the first time. If this hangs, retry with "--start-at 'comment import test again'"
  command: python3 run.py
  args:
    chdir: "{{ taranisng_root }}/taranis-ng-core/"

- name: comment import test again
  lineinfile:
    path: "{{ taranisng_root }}/taranis-ng-core/app.py"
    regexp: 'import test'
    line: '        # import test'
