version: "3.9"

services:
  redis:
    image: redis:6-alpine
    volumes: 
      - "redis_conf:/usr/local/etc/redis"

  database:
    image: postgres:13-alpine
    environment: 
      POSTGRES_DB: "taranis-ng"
      POSTGRES_USER: "taranis-ng"
      POSTGRES_PASSWORD: "supersecret"
    volumes: 
      - "database_data:/var/lib/postgresql/data"

  core:
    depends_on: 
      - "redis"
      - "database"
    build:
      context: ..
      dockerfile: ./src/Dockerfile.core
    environment: 
      REDIS_URL: "redis"
      DB_URL: "database"
      DB_DATABASE: "taranis-ng"
      DB_USER: "taranis-ng"
      DB_PASSWORD: "supersecret"
      JWT_SECRET_KEY: "supersecret"
      OPENID_LOGOUT_URL: ""
      WORKERS_PER_CORE: "1"
    ports: 
      - "5000:5000"

  bots:
    depends_on:
      - "core"
    build:
      context: ..
      dockerfile: ./src/Dockerfile.bots
    
  collectors:
    depends_on: 
      - "core"
    build:
      context: ..
      dockerfile: ./src/Dockerfile.collectors
    environment:
      FLASK_RUN_PORT: 5000
      TARANIS_NG_CORE_URL: "http://core"
      API_KEY: "supersecret"
      WORKERS_PER_CORE: "1"
    ports:
      - "5001:5000"
    
  presenters:
    depends_on: 
      - "core"
    build:
      context: ..
      dockerfile: ./src/Dockerfile.presenters
    environment:
      FLASK_RUN_PORT: 5000
      TARANIS_NG_CORE_URL: "http://core"
      API_KEY: "supersecret"
      WORKERS_PER_CORE: "1"
    ports:
      - "5002:5000"
    
  publishers:
    depends_on: 
      - "core"
    build:
      context: ..
      dockerfile: ./src/Dockerfile.publishers
    environment:
      FLASK_RUN_PORT: 5000
      TARANIS_NG_CORE_URL: "http://core"
      API_KEY: "supersecret"
      WORKERS_PER_CORE: "1"
    ports:
      - "5003:5000"
    
  gui:
    depends_on: 
      - "core"
    build:
      context: ..
      dockerfile: ./src/Dockerfile.gui
    ports: 
      - "8080:80"
    environment:
      NGINX_WORKERS: "4"
      NGINX_CONNECTIONS: "16"

volumes:
  redis_conf:
  database_data:
