- name: install the web server and configure the site
  include_tasks: webserver.yml
  when: taranisng_install_webserver

- name: upload and uncompress the static web
  unarchive:
    remote_src: yes
    src: "{{ inventory_dir }}/../files/taranis-ng-gui-dist.tar.bz2"
    dest: "{{ taranisng_root }}/taranis-ng-gui/dist/"
  when: taranisng_upload_gui_from_localhost is defined and taranisng_upload_gui_from_localhost

- name: copy the files to webserver location
  copy:
    remote_src: yes
    src: "{{ taranisng_root }}/taranis-ng-gui/dist/"
    dest: "{{ taranisng_gui_webroot }}"
    owner: "{{ taranisng_installation_user }}"
    group: "{{ taranisng_installation_group }}"
