- name: install the web server
  package:
    name:
    - apache2

- name: enable rewrite module
  apache2_module:
    name: rewrite
    state: present
  notify: apache2 restart

- name: deploy configuration file for unencrypted frontend
  template:
    src: taranis-ng-gui.conf.j2
    dest: /etc/apache2/sites-available/taranis-ng-gui.conf
  notify: apache2 restart

- name: create webroot for the frontend
  file:
    path: "{{ taranisng_gui_webroot }}"
    state: directory
    owner: "{{ taranisng_installation_user }}"
    group: "{{ taranisng_installation_group }}"

- name: enable the site
  command: a2ensite taranis-ng-gui
  notify: apache2 restart

- name: Reload if needed
  meta: flush_handlers
