- hosts: all
  become: yes
  gather_facts: true
  tasks:
  roles:
  - name: taranis-ng-os-basic
  - name: taranis-ng-build-gui
  - name: taranis-ng-deploy-gui
  - name: taranis-ng-core
  - name: taranis-ng-hosts-file
    vars:
      taranisng_api_ip: 127.0.0.1
      taranisng_gui_ip: 127.0.0.1
  - name: taranis-ng-sample-data

  vars:
    taranisng_hostname_api: api.taranisng.local
    taranisng_hostname_gui: www.taranisng.local
    taranisng_api_uri: "http://{{ taranisng_hostname_api }}/api"
    taranisng_database_password: 'CHANGEME'
    taranisng_jwt_secret_key: 'CHANGEMETOO'
    taranisng_install_keycloak: false
    taranisng_download_gui_to_localhost: false
    taranisng_upload_gui_to_localhost: false
