- hosts: all
  become: yes
  gather_facts: true

  tasks:

  roles:
  - name: taranis-ng-os-basic # basic OS setup
  - name: taranis-ng-build-gui # build a gui
  - name: taranis-ng-deploy-gui # deploy a gui (freely replace or amend)
  - name: taranis-ng-core # build and deploy API and all the rest
  - name: taranis-ng-hosts-file
    vars:
      taranisng_api_ip: 127.0.0.1
  - name: taranis-ng-sample-data

## CUSTOMIZE THESE ##

  vars:
    taranisng_hostname_api: api.taranisng.local
    taranisng_hostname_gui: www.taranisng.local
    taranisng_ssh_auth_sock: true
    taranisng_ssh_reckless: true
    taranisng_api_uri: "http://{{ taranisng_hostname_api }}/api"
    taranisng_database_password: 'Z7d46219f6e300a4'
    taranisng_jwt_secret_key: 'F1c325bc3fqq'
    taranisng_install_keycloak: false
    taranisng_download_gui_to_localhost: false
    taranisng_upload_gui_from_localhost: false

#  environment:
#    http_proxy: "http://proxy.int.sk-cert.sk:3128/"
#    https_proxy: "http://proxy.int.sk-cert.sk:3128/"
#    ftp_proxy: "http://proxy.int.sk-cert.sk:3128/"
#    HTTP_PROXY: "http://proxy.int.sk-cert.sk:3128/"
#    HTTPS_PROXY: "http://proxy.int.sk-cert.sk:3128/"
#    FTP_PROXY: "http://proxy.int.sk-cert.sk:3128/"

