- name: add the api link to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ taranisng_api_ip }} {{ taranisng_hostname_api }}"
  when: taranisng_api_ip is defined

- name: add the gui link to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ taranisng_gui_ip }} {{ taranisng_hostname_gui }}"
  when: taranisng_gui_ip is defined
