# web server
taranisng_hostname_api: api.taranisng.local

taranisng_installation_user: taranisng
taranisng_installation_group: taranisng

taranisng_install_webserver: true
taranisng_accesslog_api: "/var/log/apache2/{{ taranisng_hostname_api }}_access.log"
taranisng_errorlog_api: "/var/log/apache2/{{ taranisng_hostname_api }}_error.log"

# taranisng_jwt_secret_key: XXX not stored here, override locally

# sql database
taranisng_install_database: true
taranisng_database_host: localhost
taranisng_database_login_password: ''
taranisng_database_database: taranisng
taranisng_database_user: taranisng
# taranisng_database_password: XXX not stored here, override locally
taranisng_root: /opt/taranisng

# authentication via keycloak
taranisng_install_keycloak: true

# redis (for SSE)
taranisng_redis_url: "redis://localhost"

# repositories
taranisng_ssh_auth_sock: false
taranisng_ssh_reckless: false

taranisng_backend_repos:
- name: taranis-ng-core
  directory: taranis-ng-core
  #uri: "git@gitlab.com:sk-cert/taranis-ng-core.git"
  uri: "https://taranisng:XzoLFeDPTwgkXQGavyUj@gitlab.com/sk-cert/taranis-ng-core.git"
- name: taranis-ng-common
  directory: taranis-ng-common
  #uri: "git@gitlab.com:sk-cert/taranis-ng-common.git"
  uri: "https://taranisng:XzoLFeDPTwgkXQGavyUj@gitlab.com/sk-cert/taranis-ng-common.git"
- name: taranis-ng-collectors
  directory: taranis-ng-collectors
  #uri: "git@gitlab.com:sk-cert/taranis-ng-collectors.git"
  uri: "https://taranisng:XzoLFeDPTwgkXQGavyUj@gitlab.com/sk-cert/taranis-ng-collectors.git"
- name: taranis-ng-publishers
  directory: taranis-ng-publishers
  #uri: "git@gitlab.com:sk-cert/taranis-ng-publishers.git"
  uri: "https://taranisng:XzoLFeDPTwgkXQGavyUj@gitlab.com/sk-cert/taranis-ng-publishers.git"
- name: taranis-ng-presenters
  directory: taranis-ng-presenters
  #uri: "git@gitlab.com:sk-cert/taranis-ng-presenters.git"
  uri: "https://taranisng:XzoLFeDPTwgkXQGavyUj@gitlab.com/sk-cert/taranis-ng-presenters.git"
- name: taranis-ng-bots
  directory: taranis-ng-bots
  #uri: "git@gitlab.com:sk-cert/taranis-ng-bots.git"
  uri: "https://taranisng:XzoLFeDPTwgkXQGavyUj@gitlab.com/sk-cert/taranis-ng-bots.git"


gecko_url: "https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz"
