- name: install the dependencies for GUI build
  package:
    name:
    - npm
    - git
    state: present

- name: clone the GUI
  git:
    accept_hostkey: "{{ taranisng_ssh_reckless | bool }}"
    repo: "{{ taranisng_gui_repository }}"
    dest: "{{ taranisng_root }}/taranis-ng-gui"

- name: configure http proxy for npm
  command: "npm config set proxy {{ lookup('env','http_proxy') }}"
  when: lookup('env','http_proxy') is defined and lookup('env','http_proxy') != ''

- name: configure https proxy for npm
  command: "npm config set https-proxy {{ lookup('env','https_proxy') }}"
  when: lookup('env','https_proxy') is defined and lookup('env','https_proxy') != ''

- name: install Vue cli (may display "false positive" errors)
  npm:
    name: '@vue/cli'
    global: yes
  ignore_errors: yes

- name: install javascript prerequisites
  npm:
    path: "{{ taranisng_root }}/taranis-ng-gui/"
    state: present

- name: deploy .env that points to API
  template:
    src: env-gui.j2
    dest: "{{ taranisng_root }}/taranis-ng-gui/.env"

- name: build static frontend web page
  command:
    cmd: npm run build
    chdir: "{{ taranisng_root }}/taranis-ng-gui/"

- name: compress the static web
  archive:
    path: "{{ taranisng_root }}/taranis-ng-gui/dist/"
    dest: "{{ taranisng_root }}/taranis-ng-gui-dist.tar.bz2"
    format: bz2
  when: taranisng_download_gui_to_localhost is defined and taranisng_download_gui_to_localhost

- name: download the compressed static web locally
  fetch:
    src: "{{ taranisng_root }}/taranis-ng-gui-dist.tar.bz2"
    dest: "{{ inventory_dir }}/../files/taranis-ng-gui-dist.tar.bz2"
    flat: yes
  when: taranisng_download_gui_to_localhost is defined and taranisng_download_gui_to_localhost
